### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by yannik-b** [maxkl/StickFigureBookmarklet#1]
Please add a Usage part in your README

**Comment by maxkl** [comment]
In general, the procedure is as follows: You need to have an instance of https://github.com/maxkl/maxkl.de running, then clone this project into the `subpages/` folder. That's it.
But the details are way too complicated and time-consuming to write down, so I'm sorry but I don't have the motivation for that.

**Comment by yannik-b** [comment]
okay thx
